import deviltea from '@deviltea/eslint-config'
import pikacss from '@pikacss/eslint-config'

export default await deviltea(
	{
		markdown: {
			overrides: {
				'style/indent': ['error', 2],
			},
		},
		ignores: [
			'./.github/**/*',
			// Playground templates are standalone starters served into the
			// WebContainer; they keep their own upstream code style.
			'./playground/src/templates/**/*',
			'./playground/public/**/*',
			'./.agents/**/*',
			'.planning/**/*',
			'./docs/.examples/**/*',
			'./docs/**/*.md',
			'./skills/**/*.md',
			// Ignore the generated files
			'packages/core/src/generated/**',
			// Generated by the playground dev server (gitignored, absent in CI)
			'playground/src/vfs.d.ts',
		],
	},
	pikacss(),
)
