packages:
  - docs
  - 'examples/*'
  - 'packages/*'

catalog:
  '@clack/prompts': ^0.10.0
  '@deviltea/eslint-config': 4.0.0
  '@deviltea/tsconfig': 0.0.7
  '@iconify/utils': ^2.3.0
  '@iconify/types': ^2.0.0
  '@nuxt/kit': ^3.0.0
  '@nuxt/schema': ^3.0.0
  '@types/node': ^20
  '@types/micromatch': ^4.0.9
  '@unocss/preset-icons': ^65.4.3
  '@vitest/coverage-v8': ^3.0.9
  bumpp: ^10.0.3
  csstype: ^3.1.3
  eslint: ^9.23.0
  fast-glob: ^3.3.2
  happy-dom: ^17.4.4
  jiti: ^2.4.0
  lint-staged: ^15.5.0
  local-pkg: ^1.1.1
  magic-string: ^0.30.12
  micromatch: ^4.0.8
  ofetch: ^1.4.1
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  pkg-size: ^2.4.0
  prettier: ^3.2.5
  publint: ^0.3.9
  rimraf: ^6.0.1
  simple-git-hooks: ^2.12.1
  tsx: ^4.19.3
  typescript: ^5.8.2
  unbuild: ^3.5.0
  vite: ^6.1.1
  vitepress: ^2.0.0-alpha.2
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-tsc: ^2.2.8
  zx: ^8.4.1
