packages:
  - docs
  - packages/*

catalog:
  '@braintree/sanitize-url': ^7.1.1
  '@clack/prompts': ^0.11.0
  '@deviltea/eslint-config': 6.0.1
  '@deviltea/tsconfig': 0.0.8
  '@farmfe/core': ^1.7.11
  '@iconify-json/mdi': ^1.2.3
  '@iconify/utils': ^3.1.0
  '@nuxt/kit': ^4.2.2
  '@nuxt/schema': ^4.2.2
  '@shikijs/vitepress-twoslash': ^3.17.0
  '@types/micromatch': ^4.0.10
  '@types/node': ^24.10.1
  '@unocss/preset-icons': ^66.5.9
  '@vitest/coverage-v8': ^4.0.14
  alien-signals: ^2.0.0
  bumpp: ^10.3.2
  csstype: ^3.2.3
  cytoscape: ^3.33.1
  cytoscape-cose-bilkent: ^4.1.0
  dayjs: ^1.11.19
  debug: ^4.4.0
  esbuild: ^0.27.0
  eslint: ^9.39.1
  globby: ^16.0.0
  happy-dom: ^20.0.11
  jiti: ^2.6.1
  klona: ^2.0.6
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  magic-string: ^0.30.21
  mermaid: ^11.12.1
  micromatch: ^4.0.8
  ofetch: ^1.5.1
  pathe: ^2.0.3
  perfect-debounce: ^2.0.0
  pkg-pr-new: ^0.0.61
  pkg-size: ^2.4.0
  publint: ^0.3.15
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  tsdown: ^0.16.8
  tsx: ^4.20.6
  typescript: ^5.9.3
  unplugin: ^2.3.11
  vite: ^6.0.7
  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.6.5
  vitepress-plugin-llms: ^1.0.8
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^4.0.14
  vue: ^3.5.25
  vue-tsc: ^3.1.5
  zx: ^8.8.5

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - core-js
  - simple-git-hooks
