packages:
  - docs
  - packages/*
  - examples/*

catalog:
  '@braintree/sanitize-url': ^7.1.1
  '@clack/prompts': ^0.11.0
  '@deviltea/eslint-config': 6.0.1
  '@deviltea/tsconfig': 0.0.8
  '@iconify-json/line-md': ^1.2.11
  '@iconify-json/mdi': ^1.2.3
  '@iconify/types': ^2.0.0
  '@iconify/utils': ^3.1.0
  '@nuxt/kit': ^4.2.1
  '@nuxt/schema': ^4.2.1
  '@shikijs/vitepress-twoslash': ^3.17.0
  '@types/micromatch': ^4.0.10
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@unocss/preset-icons': ^66.5.9
  '@vitejs/plugin-react': ^5.1.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vitest/coverage-v8': ^4.0.14
  '@vue/tsconfig': ^0.8.1
  bumpp: ^10.3.2
  csstype: ^3.2.3
  cytoscape: ^3.33.1
  cytoscape-cose-bilkent: ^4.1.0
  dayjs: ^1.11.19
  debug: ^4.4.0
  eslint: ^9.39.1
  fast-glob: ^3.3.2
  globals: ^16.5.0
  happy-dom: ^20.0.11
  jiti: ^2.6.1
  klona: ^2.0.6
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  magic-string: ^0.30.21
  mermaid: ^11.12.1
  micromatch: ^4.0.8
  modern-normalize: ^3.0.1
  nuxt: ^4.2.1
  ofetch: ^1.5.1
  pathe: ^2.0.3
  perfect-debounce: ^2.0.0
  pkg-pr-new: ^0.0.61
  pkg-size: ^2.4.0
  publint: ^0.3.15
  react: ^19.2.0
  react-dom: ^19.2.0
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  solid-js: ^1.9.10
  tsdown: ^0.16.8
  tsx: ^4.20.6
  typescript: ^5.9.3
  vite: ^6.3.5
  vite-plugin-solid: ^2.11.10

  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.6.5
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^4.0.14
  vue: ^3.5.25
  vue-tsc: ^3.1.5
  zx: ^8.8.5
onlyBuiltDependencies:
  - simple-git-hooks
