packages:
  - docs
  - 'examples/*'
  - 'packages/*'

catalog:
  '@clack/prompts': ^0.10.0
  '@deviltea/eslint-config': 3.4.1
  '@deviltea/tsconfig': 0.0.7
  '@iconify/utils': ^2.3.0
  '@iconify/types': ^2.0.0
  '@nuxt/kit': ^3.0.0
  '@nuxt/schema': ^3.0.0
  '@types/node': ^20
  '@types/micromatch': ^4.0.9
  '@unocss/preset-icons': ^65.4.3
  '@vitest/coverage-v8': ^3.0.3
  bumpp: ^10.0.3
  csstype: ^3.1.3
  eslint: ^9.13.0
  fast-glob: ^3.3.2
  happy-dom: ^15.7.4
  jiti: ^2.4.0
  lint-staged: ^15.4.1
  local-pkg: ^0.4.3
  magic-string: ^0.30.12
  micromatch: ^4.0.8
  ofetch: ^1.4.1
  pathe: ^1.1.2
  perfect-debounce: ^1.0.0
  pkg-size: ^2.4.0
  prettier: ^3.2.5
  publint: ^0.2.11
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.1
  typescript: ^5.7.2
  unbuild: ^3.0.1
  vite: ^6.1.0
  vitepress: ^1.5.0
  vitest: ^3.0.3
  vue: ^3.5.13
  vue-tsc: ^2.2.0
  zx: ^8.2.0
