packages:
  - docs
  - packages/*
  - examples/*
catalog:
  '@clack/prompts': ^0.10.1
  '@deviltea/eslint-config': 6.0.1
  '@deviltea/tsconfig': 0.0.8
  '@iconify/utils': ^3.1.0
  '@iconify/types': ^2.0.0
  '@nuxt/kit': ^4.2.1
  '@nuxt/schema': ^4.2.1
  '@types/node': ^24.10.1
  '@types/micromatch': ^4.0.9
  '@unocss/preset-icons': ^66.5.9
  '@vitest/coverage-v8': ^4.0.14
  bumpp: ^10.0.3
  csstype: ^3.1.3
  eslint: ^9.39.1
  fast-glob: ^3.3.2
  happy-dom: ^20.0.0
  jiti: ^2.4.2
  lint-staged: ^16.2.7
  local-pkg: ^1.1.1
  magic-string: ^0.30.12
  micromatch: ^4.0.8
  ofetch: ^1.5.1
  pathe: ^2.0.3
  perfect-debounce: ^2.0.0
  pkg-size: ^2.4.0
  publint: ^0.3.12
  rimraf: ^6.0.1
  simple-git-hooks: ^2.13.0
  tsx: ^4.19.3
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vite: ^6.1.1
  vitepress: ^2.0.0-alpha.2
  vitest: ^4.0.14
  vue: ^3.5.13
  vue-tsc: ^3.1.5
  zx: ^8.5.3
onlyBuiltDependencies:
  - simple-git-hooks
