import type { IntegrationContext, Nullish } from '@pikacss/integration'
import type { Plugin as VitePlugin } from 'vite'
import type { PluginOptions, ResolvedPluginOptions } from './types'
import { createCtx } from '@pikacss/integration'
import { resolve } from 'pathe'
import { VIRTUAL_PIKA_CSS_ID } from './constants'

const DEV_PLUGIN_NAME = 'unplugin-pikacss:dev'
const BUILD_PLUGIN_NAME = 'unplugin-pikacss:build'
const SHARED_PLUGIN_NAME = 'unplugin-pikacss:shared'

function createPromise<T = void>() {
	let resolve: (value: T) => void
	let reject: (reason?: any) => void
	const promise = new Promise<T>((res, rej) => {
		resolve = res
		reject = rej
	})
	return { promise, resolve: resolve!, reject: reject! }
}

function dev(getCtx: () => Promise<IntegrationContext>): VitePlugin {
	let ctx: IntegrationContext = null!

	return {
		name: DEV_PLUGIN_NAME,
		enforce: 'pre',
		apply: 'serve',
		async configResolved() {
			ctx = await getCtx()
		},
		configureServer(server) {
			server.watcher.add(ctx.configSources)
			server.watcher.on('add', handleFileChange)
			server.watcher.on('unlink', handleFileChange)
			server.watcher.on('change', handleFileChange)
			async function handleFileChange(file: string) {
				if (ctx.configSources.includes(file)) {
					const moduleIds = Array.from(ctx.usages.keys())
					await ctx.init()
					moduleIds.forEach((id) => {
						const mod = server.moduleGraph.getModuleById(id)
						if (mod) {
							server.moduleGraph.invalidateModule(mod)
							server.reloadModule(mod)
						}
					})
				}
			}
		},
		buildStart() {
			ctx.hooks.styleUpdated.on(() => ctx.writeDevCssFile())
			ctx.hooks.tsCodegenUpdated.on(() => ctx.writeTsCodegenFile())
		},
		resolveId(id) {
			if (id === VIRTUAL_PIKA_CSS_ID)
				return ctx.devCssFilepath

			return void 0
		},
		transform: (code, id) => {
			return ctx.transform(code, id)
		},
	}
}

function build(getCtx: () => Promise<IntegrationContext>): VitePlugin {
	// REF: https://github.com/unocss/unocss/blob/916bd6d41690177bbdada958a2ae85a3a160a857/packages/vite/src/modes/global/build.ts#L34
	// use maps to differentiate multiple build. using outDir as key
	const cssPostPlugins = new Map<string | Nullish, VitePlugin | Nullish>()
	const cssPlugins = new Map<string | Nullish, VitePlugin | Nullish>()

	async function applyCssTransform(css: string, id: string, dir: string | Nullish, rollupCtx: any /* RollupPluginContext */) {
		// TODO: check if postcss is enabled
		const postcss = true
		if (!cssPlugins.get(dir) || !postcss)
			return css
		// @ts-expect-error without this context absolute assets will throw an error
		const result = await cssPlugins.get(dir).transform.call(rollupCtx, css, id)
		if (!result)
			return css
		if (typeof result === 'string')
			css = result
		else if (result.code)
			css = result.code
		css = css.replace(/[\n\r]/g, '')
		return css
	}

	let ctx: IntegrationContext = null!

	return {
		name: BUILD_PLUGIN_NAME,
		enforce: 'pre',
		apply: 'build',
		async configResolved(config) {
			ctx = await getCtx()

			const distDirs = [
				resolve(config.root, config.build.outDir),
			]

			const cssPostPlugin = config.plugins.find(i => i.name === 'vite:css-post') as VitePlugin | Nullish
			if (cssPostPlugin)
				distDirs.forEach(dir => cssPostPlugins.set(dir, cssPostPlugin))

			const cssPlugin = config.plugins.find(i => i.name === 'vite:css') as VitePlugin | Nullish
			if (cssPlugin)
				distDirs.forEach(dir => cssPlugins.set(dir, cssPlugin))
		},
		resolveId(id) {
			if (id === VIRTUAL_PIKA_CSS_ID)
				return id

			return null
		},
		load(id) {
			if (id === VIRTUAL_PIKA_CSS_ID)
				return ''

			return null
		},
		transform: (code, id) => {
			return ctx.transform(code, id)
		},
		async renderChunk(_, chunk, options) {
			if (!Object.keys(chunk.modules)
				.some(i => i.includes(VIRTUAL_PIKA_CSS_ID))) {
				return null
			}

			const cssPost = cssPostPlugins.get(options.dir)
			if (!cssPost) {
				this.warn('[pikacss] failed to find vite:css-post plugin. It might be an internal bug of PikaCSS')
				return null
			}

			await ctx.writeTsCodegenFile()
			const fakeCssId = `${ctx.cwd}/${chunk.fileName}-pikacss-hash.css`
			const css = await applyCssTransform(
				[
					`/* Auto-generated by ${ctx.currentPackageName} */`,
					...await ctx.engine.renderPreflights(false),
					...await ctx.engine.renderAtomicStyles(false),
				].join('\n')
					.trim(),
				fakeCssId,
				options.dir,
				this,
			)
			const transformHandler = 'handler' in cssPost.transform!
				? cssPost.transform.handler
				: cssPost.transform!
			await transformHandler.call({} as any, css, fakeCssId)

			delete chunk.modules[VIRTUAL_PIKA_CSS_ID]
			chunk.modules[fakeCssId] = {
				code: null,
				originalLength: 0,
				removedExports: [],
				renderedExports: [],
				renderedLength: 0,
			}

			return null
		},
	}
}

/**
 * Vite plugin for PikaCSS
 *
 * This is the full-featured Vite plugin with support for:
 * - Dev server hot reloading
 * - Build optimizations with CSS post-processing
 * - Virtual CSS module support
 */
export default function PikaCSSVitePlugin({
	currentPackageName = '@pikacss/unplugin-pikacss',
	config: configOrPath,
	tsCodegen = true,
	devCss = 'pika.dev.css',
	target = ['**/*.vue', '**/*.tsx', '**/*.jsx'],
	fnName = 'pika',
	transformedFormat = 'string',
	autoCreateConfig = true,
}: PluginOptions = {}): VitePlugin[] & { getCtx: () => Promise<IntegrationContext> } {
	const resolvedOptions: ResolvedPluginOptions = {
		currentPackageName,
		configOrPath,
		tsCodegen: tsCodegen === true ? 'pika.gen.ts' : tsCodegen,
		devCss,
		target,
		fnName,
		transformedFormat,
		autoCreateConfig,
	}

	const { promise, resolve } = createPromise<IntegrationContext>()
	function getCtx() {
		return promise
	}

	const plugin = [
		{
			name: SHARED_PLUGIN_NAME,
			enforce: 'pre',
			async configResolved(config) {
				resolve(await createCtx({
					cwd: config.root,
					...resolvedOptions,
				}))
			},
		} satisfies VitePlugin,
		dev(getCtx),
		build(getCtx),
	] as any as VitePlugin[] & { getCtx: () => Promise<IntegrationContext> }
	plugin.getCtx = getCtx
	return plugin
}

export { VIRTUAL_PIKA_CSS_ID } from './constants'
export * from '@pikacss/integration'

export type {
	PluginOptions,
}
