import type { DirectoryNode, FileNode, FileSystemTree } from '@webcontainer/api'
import type { Plugin } from 'vite'
import { Buffer } from 'node:buffer'
import fs from 'node:fs'
import path from 'node:path'
import ignore from 'ignore'
import isBinaryPath from 'is-binary-path'

export interface VfsPluginOptions {
	/**
	 * Directory containing the templates to be served as virtual modules.
	 * e.g. 'src/templates'
	 */
	dir: string
	/**
	 * Output path for the generated d.ts file.
	 * Defaults to 'src/vfs.d.ts'
	 */
	dts?: string
}

export function vfsPlugin(options: VfsPluginOptions): Plugin {
	const templateDir = path.resolve(options.dir)
	const dtsPath = path.resolve(options.dts || 'src/vfs.d.ts')

	return {
		name: 'vite-plugin-vfs',
		enforce: 'pre',

		configResolved(_config) {
			// Generate d.ts file
			const templates = fs.readdirSync(templateDir)
				.filter((name) => {
					const fullPath = path.join(templateDir, name)
					return fs.statSync(fullPath)
						.isDirectory()
				})

			const decls = templates.map(t => `
declare module 'virtual:template:${t}' {
    import type { FileSystemTree } from '@webcontainer/api';
    const tree: FileSystemTree;
    export default tree;
}`)
				.join('\n')

			const content = `// Auto-generated by vite-plugin-vfs
${decls}
`
			fs.writeFileSync(dtsPath, content, 'utf-8')
		},

		async resolveId(source, _importer) {
			if (source.startsWith('virtual:template:')) {
				const templateName = source.replace('virtual:template:', '')
				return `\0` + `virtual:template:${templateName}`
			}
			return null
		},

		async load(id) {
			if (id.startsWith('\0virtual:template:')) {
				const templateName = id.replace('\0virtual:template:', '')
				const dirPath = path.join(templateDir, templateName)

				if (!fs.existsSync(dirPath) || !fs.statSync(dirPath)
					.isDirectory()) {
					throw new Error(`[vite-plugin-vfs] Template directory not found: ${dirPath}`)
				}

				// Initialize ignore filter
				const ig = ignore()
				const gitignorePath = path.join(dirPath, '.gitignore')
				if (fs.existsSync(gitignorePath)) {
					ig.add(fs.readFileSync(gitignorePath, 'utf-8'))
				}
				// Always ignore .git and node_modules
				ig.add('.git')
				ig.add('node_modules')

				const buildTree = (currentDir: string, relativePath: string = ''): FileSystemTree => {
					const tree: FileSystemTree = {}
					const entries = fs.readdirSync(currentDir, { withFileTypes: true })

					for (const entry of entries) {
						const entryRelativePath = relativePath ? `${relativePath}/${entry.name}` : entry.name

						// Check ignore
						if (ig.ignores(entryRelativePath)) {
							continue
						}

						const fullPath = path.join(currentDir, entry.name)

						if (entry.isDirectory()) {
							const children = buildTree(fullPath, entryRelativePath)
							const dirNode: DirectoryNode = {
								directory: children,
							}
							tree[entry.name] = dirNode
						}
						else if (entry.isFile()) {
							const isBinary = isBinaryPath(entry.name)
							if (isBinary) {
								const content = fs.readFileSync(fullPath)
								const fileNode: FileNode = {
									file: {
										contents: content,
									},
								}
								tree[entry.name] = fileNode
							}
							else {
								const content = fs.readFileSync(fullPath, 'utf-8')
								const fileNode: FileNode = {
									file: {
										contents: content,
									},
								}
								tree[entry.name] = fileNode
							}
						}
					}
					return tree
				}

				const vfs = buildTree(dirPath)

				// Helper to generate code string from the tree
				const generateCode = (tree: FileSystemTree): string => {
					const properties = Object.entries(tree)
						.map(([key, value]) => {
							const keyStr = JSON.stringify(key)
							if ('directory' in value) {
								return `${keyStr}: { directory: ${generateCode(value.directory)} }`
							}
							else if ('file' in value) {
								const fileVal = value.file
								if ('contents' in fileVal) {
									const contents = fileVal.contents
									if (contents instanceof Uint8Array || Buffer.isBuffer(contents)) {
									// Convert Buffer/Uint8Array to base64 for transport, then back to Uint8Array at runtime
										const base64 = contents.toString('base64')
										return `${keyStr}: { file: { contents: Uint8Array.from(atob("${base64}"), c => c.charCodeAt(0)) } }`
									}
									else {
										return `${keyStr}: { file: { contents: ${JSON.stringify(contents)} } }`
									}
								}
							}
							return ''
						})
						.filter(Boolean)

					return `{ ${properties.join(', ')} }`
				}

				return `export default ${generateCode(vfs)};`
			}
			return null
		},
	}
}
