/* eslint-disable no-template-curly-in-string */
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { log } from '@pikacss/core'
import { join } from 'pathe'

import { afterEach, describe, expect, it, vi } from 'vitest'
import { createCtx } from './ctx'

const WORKSPACE_CWD = process.cwd()
const CORE_INDEX_SPECIFIER = new URL('../../core/src/index.ts', import.meta.url).href

const createdDirs: string[] = []

async function createTempDir() {
	const dir = await mkdtemp(join(tmpdir(), 'pikacss-integration-'))
	createdDirs.push(dir)
	return dir
}

function createOptions(overrides?: Partial<Parameters<typeof createCtx>[0]>) {
	return {
		cwd: '/tmp/pikacss-integration',
		currentPackageName: '@pikacss/core',
		scan: {
			include: ['src/**/*.ts'],
			exclude: [],
		},
		configOrPath: {},
		fnName: 'pika',
		transformedFormat: 'string' as const,
		tsCodegen: 'generated/pika.gen.ts' as const,
		cssCodegen: 'generated/pika.gen.css',
		autoCreateConfig: false,
		...overrides,
	}
}

async function withProcessCwd<T>(cwd: string, run: () => Promise<T>) {
	const previousCwd = process.cwd()
	process.chdir(cwd)

	try {
		return await run()
	}
	finally {
		process.chdir(previousCwd)
	}
}

afterEach(async () => {
	vi.restoreAllMocks()
	vi.doUnmock('@pikacss/core')
	vi.doUnmock('./ctx.transform-utils')
	vi.resetModules()
	log.setWarnFn(console.warn.bind(console))
	log.setErrorFn(console.error.bind(console))

	while (createdDirs.length > 0) {
		await rm(createdDirs.pop()!, { recursive: true, force: true })
	}
	process.chdir(WORKSPACE_CWD)
})

describe('createCtx', () => {
	it('sets up an inline engine, transforms style calls, and writes generated assets', async () => {
		const cwd = await createTempDir()
		const existingPlugin = { name: 'existing-plugin' }
		const inlineConfig = {
			preflights: [
				{ body: { color: 'red' } },
			],
			plugins: [existingPlugin],
		}
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: inlineConfig,
		}))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		inlineConfig.preflights = []

		expect(ctx.resolvedConfig?.preflights)
			.toHaveLength(1)
		expect(ctx.resolvedConfig?.plugins?.map(plugin => plugin.name))
			.toEqual(['@pikacss/integration:dev', 'existing-plugin'])
		expect(ctx.transformFilter.exclude)
			.toEqual([
				join(cwd, 'generated/pika.gen.css'),
				join(cwd, 'generated/pika.gen.ts'),
			])

		const transformed = await ctx.transform([
			'const a = pika({ color: \'red\' })',
			'const b = pika.str({ color: \'blue\' })',
			'const c = pikap.arr({ color: \'green\' })',
		].join('\n'), 'src/demo.ts')

		expect(transformed?.code.includes('pika('))
			.toBe(false)
		expect(transformed?.code.includes('pikap.arr('))
			.toBe(false)
		expect(transformed?.code.includes('['))
			.toBe(true)
		expect(ctx.usages.get('src/demo.ts'))
			.toHaveLength(3)
		expect(onStyleUpdated)
			.toHaveBeenCalled()
		expect(onTsUpdated)
			.toHaveBeenCalled()

		const cssContent = await ctx.getCssCodegenContent()
		const tsContent = await ctx.getTsCodegenContent()

		expect(cssContent)
			.toContain('/* Auto-generated by @pikacss/core */')
		expect(cssContent)
			.toContain('color: red;')
		expect(tsContent)
			.toContain('declare global {')
		expect(tsContent)
			.toContain('const pika: StyleFn')

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		expect(await readFile(join(cwd, 'generated/pika.gen.css'), 'utf8'))
			.toBe(cssContent)
		expect(await readFile(join(cwd, 'generated/pika.gen.ts'), 'utf8'))
			.toBe(tsContent)
	})

	it('returns null when transform is called before setup initializes the engine', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		expect(await ctx.transform('const value = pika({ color: \'red\' })', 'src/before-setup.ts'))
			.toBeNull()
	})

	it('exposes path getters, updates cwd, and throws when engine is accessed before setup', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		await mkdir(join(nextCwd, 'node_modules/vue'), { recursive: true })
		await writeFile(join(nextCwd, 'node_modules/vue/package.json'), '{"name":"vue","version":"0.0.0"}')
		const ctx = createCtx(createOptions({
			cwd,
			cssCodegen: '/tmp/pikacss-fixed.css',
			tsCodegen: '/tmp/pikacss-fixed.ts',
		}))

		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
		expect(ctx.cssCodegenFilepath)
			.toBe('/tmp/pikacss-fixed.css')
		expect(ctx.tsCodegenFilepath)
			.toBe('/tmp/pikacss-fixed.ts')
		expect(ctx.hasVue)
			.toBe(false)

		ctx.cwd = nextCwd

		expect(ctx.cwd)
			.toBe(nextCwd)
		expect(ctx.hasVue)
			.toBe(true)
	})

	it('auto-creates and loads a config scaffold when no config file exists', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			currentPackageName: CORE_INDEX_SPECIFIER,
			configOrPath: null,
			autoCreateConfig: true,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		const configPath = join(cwd, 'pika.config.js')
		const content = await readFile(configPath, 'utf8')

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		expect(ctx.resolvedConfigContent)
			.toContain('defineEngineConfig')
		expect(ctx.resolvedConfig?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
		expect(content)
			.toContain('/// <reference path="./generated/pika.gen.ts" />')
		expect(content)
			.toContain(`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`)
	})

	it('auto-creates a scaffold without a ts reference when TypeScript codegen is disabled', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			currentPackageName: CORE_INDEX_SPECIFIER,
			configOrPath: null,
			autoCreateConfig: true,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		const content = await readFile(join(cwd, 'pika.config.js'), 'utf8')

		expect(content.includes('/// <reference path='))
			.toBe(false)
	})

	it('discovers an existing config file from the scan pattern when no explicit path is provided', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pikacss.config.ts'), [
			`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`,
			'',
			'export default defineEngineConfig({',
			'  preflights: [{ body: { color: \'orange\' } }],',
			'})',
		].join('\n'))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(join(cwd, 'pikacss.config.ts'))
		expect(ctx.resolvedConfigContent)
			.toContain('orange')
		expect(await ctx.getCssCodegenContent())
			.toContain('color: orange;')
	})

	it('returns undefined when no function call matches and when argument evaluation fails', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		expect(await ctx.transform('const plain = 1', 'src/plain.ts'))
			.toBeUndefined()

		const valid = await ctx.transform('const value = pika({ color: \'red\' })', 'src/broken.ts')
		expect(valid)
			.toBeDefined()
		expect(ctx.usages.has('src/broken.ts'))
			.toBe(true)

		const invalid = await ctx.transform('const broken = pika(foo())', 'src/broken.ts')
		expect(invalid)
			.toBeUndefined()
		expect(ctx.usages.has('src/broken.ts'))
			.toBe(false)
	})

	it('handles bracket-call variants, nested template expressions, and comments while transforming', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			transformedFormat: 'array',
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'const a = pika[\'str\']({ color: \'red\' /* inline comment */ })',
			'const b = pika[`arr`]({ content: `calc(${`1`})` })',
			'const c = pikap({ color: \'blue\' // trailing comment\n})',
		].join('\n'), 'src/complex.ts')

		expect(transformed?.code)
			.toContain('[')
		expect(transformed?.code.includes('pika['))
			.toBe(false)
		expect(ctx.usages.get('src/complex.ts'))
			.toHaveLength(3)
	})

	it('warns and skips malformed template, comment, and unterminated call patterns', async () => {
		const cwd = await createTempDir()
		const warn = vi.fn()
		log.setWarnFn(warn)
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		expect(await ctx.transform('const a = pika({ color: `red ${`', 'src/malformed-template.ts'))
			.toBeUndefined()
		expect(await ctx.transform('const b = pika({ color: \'red\' /*', 'src/unclosed-comment.ts'))
			.toBeUndefined()
		expect(await ctx.transform('const c = pika({ color: \'red\' //', 'src/unclosed-line-comment.ts'))
			.toBeUndefined()

		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('Malformed template literal expression in function call')))
			.toBe(true)
		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('Unclosed comment in function call')))
			.toBe(true)
		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('Unclosed function call')))
			.toBe(true)
		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('Malformed function call')))
			.toBe(true)
	})

	it('skips TypeScript generation when it is disabled and performs full CSS scanning', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src', 'demo.ts'), 'export const value = pika({ color: \'red\' })')
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await readFile(join(cwd, 'generated/pika.gen.css'), 'utf8'))
			.toContain('/* Auto-generated by @pikacss/core */')
	})

	it('honors explicit config paths and leaves tsCodegen excludes empty when disabled', async () => {
		const cwd = await createTempDir()
		const configPath = join(cwd, 'configs/pikacss.config.ts')
		await mkdir(join(cwd, 'configs'), { recursive: true })
		await writeFile(configPath, [
			`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`,
			'',
			'export default defineEngineConfig({',
			'  preflights: [{ body: { color: \'purple\' } }],',
			'})',
		].join('\n'))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: 'configs/pikacss.config.ts',
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		expect(ctx.transformFilter.exclude)
			.toEqual([
				join(cwd, 'generated/pika.gen.css'),
			])
		expect(await ctx.getCssCodegenContent())
			.toContain('color: purple;')
	})

	it('returns null config data when config lookup is disabled or the path extension is invalid', async () => {
		const cwd = await createTempDir()
		const warn = vi.fn()
		log.setWarnFn(warn)
		const disabledLookup = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
			tsCodegen: false,
		}))
		const invalidExt = createCtx(createOptions({
			cwd,
			configOrPath: 'pika.config.txt',
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			expect(await disabledLookup.loadConfig())
				.toEqual({ config: null, file: null, content: null })
			expect(await invalidExt.loadConfig())
				.toEqual({ config: null, file: null, content: null })
		})

		expect(disabledLookup.resolvedConfigPath)
			.toBeNull()
		expect(invalidExt.resolvedConfigPath)
			.toBeNull()
		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('Config file not found and autoCreateConfig is false')))
			.toBe(true)
	})

	it('sets up a default engine config when no config file is available', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfig)
			.toBeNull()
		expect(ctx.engine.config.plugins?.some(plugin => plugin.name === '@pikacss/integration:dev'))
			.toBe(true)
	})

	it('returns null config data when an existing config file throws during evaluation', async () => {
		const cwd = await createTempDir()
		const error = vi.fn()
		log.setErrorFn(error)
		const configPath = join(cwd, 'pika.config.ts')
		await writeFile(configPath, 'throw new Error("invalid config")')

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			expect(await ctx.loadConfig())
				.toEqual({ config: null, file: null, content: null })
		})

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to load config file: invalid config')))
			.toBe(true)
	})

	it('skips writing generated files when the derived content is null', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		vi.spyOn(ctx, 'getCssCodegenContent')
			.mockResolvedValueOnce(null)
		vi.spyOn(ctx, 'getTsCodegenContent')
			.mockResolvedValueOnce(null)

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		expect(ctx.cssCodegenFilepath)
			.toBe(join(cwd, 'generated/pika.gen.css'))
		expect(ctx.tsCodegenFilepath)
			.toBe(join(cwd, 'generated/pika.gen.ts'))
	})

	it('returns early when TypeScript codegen is disabled and when css output collapses to only the banner', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await ctx.setup()
		vi.spyOn(ctx.engine, 'renderLayerOrderDeclaration')
			.mockReturnValue('')
		vi.spyOn(ctx.engine, 'renderPreflights')
			.mockResolvedValue('')
		vi.spyOn(ctx.engine, 'renderAtomicStyles')
			.mockResolvedValue('')

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await ctx.getCssCodegenContent())
			.toBe('/* Auto-generated by @pikacss/core */')

		await ctx.writeTsCodegenFile()
	})

	it('retries engine creation with a default plugin-only config when the initial createEngine call fails', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, unknown>) => {
				if (createEngine.mock.calls.length === 1) {
					throw new Error('boom')
				}

				return {
					config,
					use: vi.fn(async () => []),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'generated/pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect((core.createEngine as any).mock.calls)
			.toHaveLength(2)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins)
			.toHaveLength(1)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
	})

	it('logs and clears setupPromise when both engine creation attempts fail', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async () => {
				throw new Error('still broken')
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const error = vi.fn()
		core.log.setErrorFn(error)
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'generated/pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to setup integration context: still broken')))
			.toBe(true)
		expect(ctx.setupPromise)
			.toBeNull()
	})

	it('returns undefined when the parser yields an unsupported function variant', async () => {
		vi.doMock('./ctx.transform-utils', async (importOriginal) => {
			const actual = await importOriginal<typeof import('./ctx.transform-utils')>()
			return {
				...actual,
				createFnUtils: () => ({
					isNormal: () => false,
					isForceString: () => false,
					isForceArray: () => false,
					isPreview: () => false,
					RE: /pika\(/g,
				}),
				findFunctionCalls: () => ([
					{
						fnName: 'pika.invalid',
						start: 14,
						end: 45,
						snippet: 'pika.invalid({ color: \'red\' })',
					},
				]),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-integration',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'generated/pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect(await ctx.transform('const value = pika({ color: \'red\' })', 'src/unexpected.ts'))
			.toBeUndefined()
	})

	it('swallows mkdir errors and still writes the generated file when the directory already exists', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'generated'), { recursive: true })

		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				mkdir: vi.fn()
					.mockRejectedValue(new Error('EACCES: permission denied')),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await ctx.setup()
		await ctx.writeCssCodegenFile()

		const content = await readFile(join(cwd, 'generated/pika.gen.css'), 'utf-8')
		expect(content)
			.toContain('Auto-generated')
	})
})
