/* eslint-disable no-template-curly-in-string */
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { log } from '@pikacss/core'
import { join } from 'pathe'

import { afterEach, describe, expect, it, vi } from 'vitest'
import { createDeferred } from '../../_shared/vitest'
import { createCtx } from './ctx'

const WORKSPACE_CWD = process.cwd()
const CORE_INDEX_SPECIFIER = new URL('../../core/src/index.ts', import.meta.url).href

const createdDirs: string[] = []

async function createTempDir() {
	const dir = await mkdtemp(join(tmpdir(), 'pikacss-integration-'))
	createdDirs.push(dir)
	return dir
}

function createOptions(overrides?: Partial<Parameters<typeof createCtx>[0]>) {
	return {
		cwd: '/tmp/pikacss-integration',
		currentPackageName: '@pikacss/core',
		scan: {
			include: ['src/**/*.ts'],
			exclude: [],
		},
		configOrPath: {},
		fnName: 'pika',
		transformedFormat: 'string' as const,
		tsCodegen: 'generated/pika.gen.ts' as const,
		cssCodegen: 'generated/pika.gen.css',
		autoCreateConfig: false,
		...overrides,
	}
}

async function withProcessCwd<T>(cwd: string, run: () => Promise<T>) {
	const previousCwd = process.cwd()
	process.chdir(cwd)

	try {
		return await run()
	}
	finally {
		process.chdir(previousCwd)
	}
}

afterEach(async () => {
	vi.restoreAllMocks()
	vi.doUnmock('@pikacss/core')
	vi.doUnmock('./ctx.transform-utils')
	vi.resetModules()
	log.setWarnFn(console.warn.bind(console))
	log.setErrorFn(console.error.bind(console))

	while (createdDirs.length > 0) {
		await rm(createdDirs.pop()!, { recursive: true, force: true })
	}
	process.chdir(WORKSPACE_CWD)
})

describe('createCtx', () => {
	it('sets up an inline engine, transforms style calls, and writes generated assets', async () => {
		const cwd = await createTempDir()
		const existingPlugin = { name: 'existing-plugin' }
		const inlineConfig = {
			preflights: [
				{ body: { color: 'red' } },
			],
			plugins: [existingPlugin],
		}
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: inlineConfig,
		}))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		inlineConfig.preflights = []

		expect(ctx.resolvedConfig?.preflights)
			.toHaveLength(1)
		expect(ctx.resolvedConfig?.plugins?.map(plugin => plugin.name))
			.toEqual(['@pikacss/integration:dev', 'existing-plugin'])
		expect(ctx.transformFilter.exclude)
			.toEqual([
				'generated/pika.gen.css',
				'generated/pika.gen.ts',
			])

		const transformed = await ctx.transform([
			'const a = pika({ color: \'red\' })',
			'const b = pika.str({ color: \'blue\' })',
			'const c = pikap.arr({ color: \'green\' })',
		].join('\n'), 'src/demo.ts')

		expect(transformed?.code.includes('pika('))
			.toBe(false)
		expect(transformed?.code.includes('pikap.arr('))
			.toBe(false)
		expect(transformed?.code.includes('['))
			.toBe(true)
		expect(ctx.usages.get('src/demo.ts'))
			.toHaveLength(3)
		expect(ctx.previewUsages.get('src/demo.ts'))
			.toHaveLength(1)
		expect(ctx.previewUsages.get('src/demo.ts')![0]!.params)
			.toEqual([{ color: 'green' }])
		expect(onStyleUpdated)
			.toHaveBeenCalled()
		expect(onTsUpdated)
			.toHaveBeenCalled()

		const cssContent = await ctx.getCssCodegenContent()
		const tsContent = await ctx.getTsCodegenContent()

		expect(cssContent)
			.toContain('/* Auto-generated by @pikacss/core */')
		expect(cssContent)
			.toContain('color: red;')
		expect(tsContent)
			.toContain('declare global {')
		expect(tsContent)
			.toContain('const pika: StyleFn')

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		expect(await readFile(join(cwd, 'generated/pika.gen.css'), 'utf8'))
			.toBe(cssContent)
		expect(await readFile(join(cwd, 'generated/pika.gen.ts'), 'utf8'))
			.toBe(tsContent)
	})

	it('returns null when transform is called before setup initializes the engine', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		expect(await ctx.transform('const value = pika({ color: \'red\' })', 'src/before-setup.ts'))
			.toBeNull()
	})

	it('exposes path getters, updates cwd, and throws when engine is accessed before setup', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		await mkdir(join(nextCwd, 'node_modules/vue'), { recursive: true })
		await writeFile(join(nextCwd, 'node_modules/vue/package.json'), '{"name":"vue","version":"0.0.0"}')
		const ctx = createCtx(createOptions({
			cwd,
			cssCodegen: '/tmp/pikacss-fixed.css',
			tsCodegen: '/tmp/pikacss-fixed.ts',
		}))

		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
		expect(ctx.cssCodegenFilepath)
			.toBe('/tmp/pikacss-fixed.css')
		expect(ctx.tsCodegenFilepath)
			.toBe('/tmp/pikacss-fixed.ts')
		expect(ctx.hasVue)
			.toBe(false)

		ctx.cwd = nextCwd

		expect(ctx.cwd)
			.toBe(nextCwd)
		expect(ctx.hasVue)
			.toBe(true)
	})

	it('auto-creates and loads a config scaffold when no config file exists', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			currentPackageName: CORE_INDEX_SPECIFIER,
			configOrPath: null,
			autoCreateConfig: true,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		const configPath = join(cwd, 'pika.config.js')
		const content = await readFile(configPath, 'utf8')

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		expect(ctx.resolvedConfigContent)
			.toContain('defineEngineConfig')
		expect(ctx.resolvedConfig?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
		expect(content)
			.toContain('/// <reference path="./generated/pika.gen.ts" />')
		expect(content)
			.toContain(`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`)
	})

	it('auto-creates a scaffold without a ts reference when TypeScript codegen is disabled', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			currentPackageName: CORE_INDEX_SPECIFIER,
			configOrPath: null,
			autoCreateConfig: true,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		const content = await readFile(join(cwd, 'pika.config.js'), 'utf8')

		expect(content.includes('/// <reference path='))
			.toBe(false)
	})

	it('discovers an existing config file from the scan pattern when no explicit path is provided', async () => {
		const cwd = await createTempDir()
		await writeFile(join(cwd, 'pikacss.config.ts'), [
			`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`,
			'',
			'export default defineEngineConfig({',
			'  preflights: [{ body: { color: \'orange\' } }],',
			'})',
		].join('\n'))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(join(cwd, 'pikacss.config.ts'))
		expect(ctx.resolvedConfigContent)
			.toContain('orange')
		expect(await ctx.getCssCodegenContent())
			.toContain('color: orange;')
	})

	it('returns undefined when no function call matches and when argument evaluation fails', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		expect(await ctx.transform('const plain = 1', 'src/plain.ts'))
			.toBeUndefined()

		const valid = await ctx.transform('const value = pika({ color: \'red\' })', 'src/broken.ts')
		expect(valid)
			.toBeDefined()
		expect(ctx.usages.has('src/broken.ts'))
			.toBe(true)
		expect(ctx.previewUsages.has('src/broken.ts'))
			.toBe(false)

		const invalid = await ctx.transform('const broken = pika(foo())', 'src/broken.ts')
		expect(invalid)
			.toBeUndefined()
		expect(ctx.usages.has('src/broken.ts'))
			.toBe(false)
		expect(ctx.previewUsages.has('src/broken.ts'))
			.toBe(false)
	})

	it('triggers regeneration when the last style call is removed from a file', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		ctx.hooks.styleUpdated.on(onStyleUpdated)

		await ctx.transform('const value = pika({ color: \'red\' })', 'src/removed.ts')
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)

		await ctx.transform('const value = 1', 'src/removed.ts')
		expect(ctx.usages.has('src/removed.ts'))
			.toBe(false)
		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(2)
	})

	it('keeps valid calls when a sibling call in the same file fails to evaluate', async () => {
		const cwd = await createTempDir()
		const error = vi.fn()
		log.setErrorFn(error)
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		const result = await ctx.transform([
			'const ok = pika({ color: \'red\' })',
			'const broken = pika({ color: localVariable })',
		].join('\n'), 'src/partial.ts')

		expect(result?.code)
			.toContain('\'pk-')
		expect(result?.code)
			.toContain('pika({ color: localVariable })')
		expect(ctx.usages.get('src/partial.ts'))
			.toHaveLength(1)
		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to transform')))
			.toBe(true)
	})

	it('handles bracket-call variants, nested template expressions, and comments while transforming', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			transformedFormat: 'array',
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'const a = pika[\'str\']({ color: \'red\' /* inline comment */ })',
			'const b = pika[`arr`]({ content: `calc(${`1`})` })',
			'const c = pikap({ color: \'blue\' // trailing comment\n})',
		].join('\n'), 'src/complex.ts')

		expect(transformed?.code)
			.toContain('[')
		expect(transformed?.code.includes('pika['))
			.toBe(false)
		expect(ctx.usages.get('src/complex.ts'))
			.toHaveLength(3)
		expect(ctx.previewUsages.get('src/complex.ts'))
			.toHaveLength(1)
	})

	it('transforms pika() calls inside Vue SFC template attributes', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.{ts,vue}'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<script setup lang="ts">',
			'const fromScript = pika({ color: \'gold\' })',
			'</script>',
			'',
			'<template>',
			'\t<!-- <div :class="pika({ color: \'red\' })"> -->',
			'\t<div :class="pika({ height: \'100vh\', display: \'flex\' })">',
			'\t\t<span :class="pika({ fontSize: \'0.875rem\' })">text</span>',
			'\t</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		expect(transformed?.code.includes('pika({ color: \'gold\' })'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ height:'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ fontSize:'))
			.toBe(false)
		// The commented-out call must survive untouched.
		expect(transformed?.code)
			.toContain('<!-- <div :class="pika({ color: \'red\' })"> -->')
		// Replacements must stay single-quoted inside double-quoted attributes.
		expect(transformed?.code)
			.toMatch(/:class="'[^"]*'"/)
		expect(ctx.usages.get('src/App.vue'))
			.toHaveLength(3)
	})

	it('escapes line terminators when serializing unresolved string style items', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		// `new Function` evaluation turns the source `\n` escape into a real LF,
		// which the engine echoes back verbatim for unresolved string items.
		const transformed = await ctx.transform('const value = pika(\'a\\nb\')', 'src/newline.ts')

		expect(transformed?.code)
			.toContain('\'a\\nb\'')
		// The emitted literal must not contain a raw line terminator.
		expect(transformed?.code)
			.not.toContain('\n')
		// eslint-disable-next-line no-new-func
		expect(() => new Function(transformed!.code))
			.not.toThrow()
	})

	it('does not rewrite pika lookalikes inside script-block literals and comments of markup sources', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<script setup lang="ts">',
			'const tip = "use pika(\'bg:red\') here"',
			'// pika({ color: \'red\' })',
			'/* pika({ color: \'green\' }) */',
			'const real = pika({ color: \'gold\' })',
			'</script>',
			'',
			'<template>',
			'\t<div :class="pika({ color: \'blue\' })">real</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		// Lookalikes inside script-block literals and JS comments survive untouched.
		expect(transformed?.code)
			.toContain('const tip = "use pika(\'bg:red\') here"')
		expect(transformed?.code)
			.toContain('// pika({ color: \'red\' })')
		expect(transformed?.code)
			.toContain('/* pika({ color: \'green\' }) */')
		// Real calls in the script block and the template attribute are rewritten.
		expect(transformed?.code.includes('pika({ color: \'gold\' })'))
			.toBe(false)
		expect(transformed?.code.includes('pika({ color: \'blue\' })'))
			.toBe(false)
		expect(ctx.usages.get('src/App.vue'))
			.toHaveLength(2)
	})

	it('emits double-quoted literals inside single-quoted markup attributes', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.vue'],
				exclude: [],
			},
		}))

		await ctx.setup()

		const transformed = await ctx.transform([
			'<template>',
			'\t<div :class=\'pika({ color: "red" })\'>',
			'\t\t<span :class="pika({ color: \'blue\' })">text</span>',
			'\t</div>',
			'</template>',
		].join('\n'), 'src/App.vue')

		// Single-quoted attribute stays intact: the literal uses double quotes.
		expect(transformed?.code)
			.toMatch(/:class='"[^']*"'/)
		// Double-quoted attribute keeps the existing single-quoted output.
		expect(transformed?.code)
			.toMatch(/:class="'[^"]*'"/)
		expect(ctx.usages.get('src/App.vue'))
			.toHaveLength(2)
	})

	it('extends markup mode with user-supplied extensions while keeping the defaults', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['src/**/*.{riot,vue}'],
				exclude: [],
			},
			markupExtensions: ['riot'],
		}))

		await ctx.setup()

		const riotTransformed = await ctx.transform(
			'<div class="pika({ color: \'gold\' })"></div>',
			'src/App.riot',
		)
		const vueTransformed = await ctx.transform(
			'<template>\n\t<div :class="pika({ color: \'red\' })">\n</template>',
			'src/App.vue',
		)

		expect(riotTransformed?.code.includes('pika('))
			.toBe(false)
		expect(vueTransformed?.code.includes('pika('))
			.toBe(false)
		expect(ctx.usages.get('src/App.riot'))
			.toHaveLength(1)
		expect(ctx.usages.get('src/App.vue'))
			.toHaveLength(1)
	})

	it('buffers style and ts updates until all concurrent transforms finish', async () => {
		const firstUse = createDeferred<string[]>()
		const secondUse = createDeferred<string[]>()
		let useCallCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				const devPlugin = config.plugins?.find((plugin: any) => plugin.name === '@pikacss/integration:dev')
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					use: vi.fn(async () => {
						devPlugin?.atomicStyleAdded?.()
						devPlugin?.autocompleteConfigUpdated?.()

						useCallCount++
						return useCallCount === 1 ? firstUse.promise : secondUse.promise
					}),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions())

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		const firstTransform = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		const secondTransform = ctx.transform('const b = pika({ color: \'blue\' })', 'src/b.ts')

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		firstUse.resolve(['pk-a'])
		await firstTransform

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		secondUse.resolve(['pk-b'])
		await secondTransform

		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)
		expect(ctx.usages.get('src/a.ts')?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.usages.get('src/b.ts')?.[0]?.atomicStyleIds)
			.toEqual(['pk-b'])
	})

	it('waits for the remaining transform when a concurrent transform fails early', async () => {
		const firstUse = createDeferred<string[]>()

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				const devPlugin = config.plugins?.find((plugin: any) => plugin.name === '@pikacss/integration:dev')
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					use: vi.fn(async () => {
						devPlugin?.atomicStyleAdded?.()
						devPlugin?.autocompleteConfigUpdated?.()
						return firstUse.promise
					}),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions())

		await ctx.setup()
		const onStyleUpdated = vi.fn()
		const onTsUpdated = vi.fn()

		ctx.hooks.styleUpdated.on(onStyleUpdated)
		ctx.hooks.tsCodegenUpdated.on(onTsUpdated)

		const firstTransform = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		const failedTransform = ctx.transform('const broken = pika(foo())', 'src/b.ts')

		await failedTransform

		expect(onStyleUpdated)
			.not.toHaveBeenCalled()
		expect(onTsUpdated)
			.not.toHaveBeenCalled()

		firstUse.resolve(['pk-a'])
		await firstTransform

		expect(onStyleUpdated)
			.toHaveBeenCalledTimes(1)
		expect(onTsUpdated)
			.toHaveBeenCalledTimes(1)
		expect(ctx.usages.get('src/a.ts')?.[0]?.atomicStyleIds)
			.toEqual(['pk-a'])
		expect(ctx.usages.has('src/b.ts'))
			.toBe(false)
	})

	it('drains in-flight transforms before setup clears state and swaps the engine', async () => {
		const firstUse = createDeferred<string[]>()
		let engineCount = 0

		vi.resetModules()
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, any>) => {
				engineCount++
				const engineIndex = engineCount
				return {
					config,
					store: {
						atomicStyleIds: new Map(),
					},
					use: vi.fn(async () => engineIndex === 1 ? firstUse.promise : ['pk-new']),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions())

		await ctx.setup()

		// Suspended at the first engine's `use()` call.
		const inFlight = ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')

		let setupDone = false
		const setupPromise = ctx.setup()
			.then(() => {
				setupDone = true
			})

		// Setup must stay parked on the drain while the transform is in flight.
		await new Promise(resolve => setTimeout(resolve, 10))
		expect(setupDone)
			.toBe(false)

		firstUse.resolve(['pk-old'])
		await inFlight
		await setupPromise

		// The late transform completed before setup cleared state, so its
		// old-engine usages were not written into the new engine's session.
		expect(ctx.usages.size)
			.toBe(0)

		// A re-transform after setup records usages resolved by the new engine.
		await ctx.transform('const a = pika({ color: \'red\' })', 'src/a.ts')
		expect(ctx.usages.get('src/a.ts')?.[0]?.atomicStyleIds)
			.toEqual(['pk-new'])
	})

	it('warns and skips malformed template, comment, and unterminated call patterns', async () => {
		const cwd = await createTempDir()
		const warn = vi.fn()
		log.setWarnFn(warn)
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		expect(await ctx.transform('const a = pika({ color: `red ${`', 'src/malformed-template.ts'))
			.toBeUndefined()
		expect(await ctx.transform('const b = pika({ color: \'red\' /*', 'src/unclosed-comment.ts'))
			.toBeUndefined()
		expect(await ctx.transform('const c = pika({ color: \'red\' //', 'src/unclosed-line-comment.ts'))
			.toBeUndefined()

		expect(warn.mock.calls.filter(call => call.join(' ')
			.includes('Malformed function call')))
			.toHaveLength(3)
	})

	it('skips TypeScript generation when it is disabled and performs full CSS scanning', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src', 'demo.ts'), 'export const value = pika({ color: \'red\' })')
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await readFile(join(cwd, 'generated/pika.gen.css'), 'utf8'))
			.toContain('/* Auto-generated by @pikacss/core */')
	})

	it('evaluates transform targets against the current cwd and always rejects codegen outputs', async () => {
		const cwd = await createTempDir()
		const nextCwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			scan: {
				include: ['**/*.{ts,css}'],
				exclude: ['node_modules/**', 'dist/**', join(nextCwd, 'abs-excluded/**')],
			},
		}))

		// Relative excludes and ids must follow the updated cwd, not the one the
		// context was created with.
		ctx.cwd = nextCwd

		expect(ctx.isTransformTarget(join(nextCwd, 'src/demo.ts')))
			.toBe(true)
		// Relative ids resolve against the current cwd.
		expect(ctx.isTransformTarget('src/demo.ts'))
			.toBe(true)
		// Query/hash suffixes are ignored.
		expect(ctx.isTransformTarget(`${join(nextCwd, 'src/demo.ts')}?raw`))
			.toBe(true)
		// cwd-relative excludes are resolved against the current cwd.
		expect(ctx.isTransformTarget(join(nextCwd, 'node_modules/pkg/index.ts')))
			.toBe(false)
		expect(ctx.isTransformTarget(join(nextCwd, 'dist/out.ts')))
			.toBe(false)
		// Codegen outputs are always rejected, even when they match the include globs.
		expect(ctx.isTransformTarget(join(nextCwd, 'generated/pika.gen.ts')))
			.toBe(false)
		expect(ctx.isTransformTarget(join(nextCwd, 'generated/pika.gen.css')))
			.toBe(false)
		// Absolute exclude patterns match against the absolute id.
		expect(ctx.isTransformTarget(join(nextCwd, 'abs-excluded/skip.ts')))
			.toBe(false)
		// Non-included files are rejected.
		expect(ctx.isTransformTarget(join(nextCwd, 'README.md')))
			.toBe(false)
	})

	it('skips the codegen output files during full CSS scanning even when they match scan.include', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'src'), { recursive: true })
		await writeFile(join(cwd, 'src/demo.ts'), 'export const value = pika({ color: \'red\' })')
		// A stale codegen output that matches the include glob must not be scanned.
		const tsCodegenFilepath = join(cwd, 'src/pika.gen.ts')
		await writeFile(tsCodegenFilepath, 'export const leaked = pika({ color: \'blue\' })')

		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: 'src/pika.gen.ts',
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
			await ctx.fullyCssCodegen()
		})

		expect(ctx.usages.has(tsCodegenFilepath))
			.toBe(false)
		const css = await readFile(join(cwd, 'generated/pika.gen.css'), 'utf8')
		expect(css)
			.toContain('color: red')
		expect(css)
			.not.toContain('color: blue')
	})

	it('prunes variables and keyframes of styles whose usages were removed', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: {
				variables: {
					definitions: {
						'--main-color': 'red',
					},
				},
				keyframes: {
					definitions: [
						['spin', { from: { opacity: '0' }, to: { opacity: '1' } }],
					],
				},
			},
		}))

		await ctx.setup()

		await ctx.transform('const a = pika({ color: \'var(--main-color)\', animationName: \'spin\' })', 'src/anim.ts')
		const withUsage = await ctx.getCssCodegenContent()
		expect(withUsage)
			.toContain('--main-color')
		expect(withUsage)
			.toContain('@keyframes spin')

		// Deleting the usage (as watchChange/transform would) must drop the
		// variable and keyframes from the regenerated CSS despite the
		// append-only engine store.
		await ctx.transform('const a = 1', 'src/anim.ts')
		const withoutUsage = await ctx.getCssCodegenContent()
		expect(withoutUsage)
			.not.toContain('--main-color')
		expect(withoutUsage)
			.not.toContain('@keyframes spin')
	})

	it('honors explicit config paths and leaves tsCodegen excludes empty when disabled', async () => {
		const cwd = await createTempDir()
		const configPath = join(cwd, 'configs/pikacss.config.ts')
		await mkdir(join(cwd, 'configs'), { recursive: true })
		await writeFile(configPath, [
			`import { defineEngineConfig } from '${CORE_INDEX_SPECIFIER}'`,
			'',
			'export default defineEngineConfig({',
			'  preflights: [{ body: { color: \'purple\' } }],',
			'})',
		].join('\n'))

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: 'configs/pikacss.config.ts',
			tsCodegen: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfigPath)
			.toBe(configPath)
		expect(ctx.transformFilter.exclude)
			.toEqual([
				'generated/pika.gen.css',
			])
		expect(await ctx.getCssCodegenContent())
			.toContain('color: purple;')
	})

	it('returns null config data when config lookup is disabled or the path extension is invalid', async () => {
		const cwd = await createTempDir()
		const warn = vi.fn()
		log.setWarnFn(warn)
		const disabledLookup = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
			tsCodegen: false,
		}))
		const invalidExt = createCtx(createOptions({
			cwd,
			configOrPath: 'pika.config.txt',
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			expect(await disabledLookup.loadConfig())
				.toEqual({ config: null, file: null, content: null })
			expect(await invalidExt.loadConfig())
				.toEqual({ config: null, file: null, content: null })
		})

		expect(disabledLookup.resolvedConfigPath)
			.toBeNull()
		expect(invalidExt.resolvedConfigPath)
			.toBeNull()
		expect(warn.mock.calls.some(call => call.join(' ')
			.includes('Config file not found and autoCreateConfig is false')))
			.toBe(true)
	})

	it('sets up a default engine config when no config file is available', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: null,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			await ctx.setup()
		})

		expect(ctx.resolvedConfig)
			.toBeNull()
		expect(ctx.engine.config.plugins?.some(plugin => plugin.name === '@pikacss/integration:dev'))
			.toBe(true)
	})

	it('keeps the config file path and content when the config file throws during evaluation', async () => {
		const cwd = await createTempDir()
		const error = vi.fn()
		log.setErrorFn(error)
		const configPath = join(cwd, 'pika.config.ts')
		const configContent = 'throw new Error("invalid config")'
		await writeFile(configPath, configContent)

		const ctx = createCtx(createOptions({
			cwd,
			configOrPath: configPath,
			autoCreateConfig: false,
		}))

		await withProcessCwd(cwd, async () => {
			// The path and content are preserved so integrations can keep
			// watching the config file and reload once the user fixes it.
			expect(await ctx.loadConfig())
				.toEqual({ config: null, file: configPath, content: configContent })
		})

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to evaluate config file: invalid config')))
			.toBe(true)
	})

	it('skips writing generated files when the derived content is null', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({ cwd }))

		await ctx.setup()

		vi.spyOn(ctx, 'getCssCodegenContent')
			.mockResolvedValueOnce(null)
		vi.spyOn(ctx, 'getTsCodegenContent')
			.mockResolvedValueOnce(null)

		await ctx.writeCssCodegenFile()
		await ctx.writeTsCodegenFile()

		expect(ctx.cssCodegenFilepath)
			.toBe(join(cwd, 'generated/pika.gen.css'))
		expect(ctx.tsCodegenFilepath)
			.toBe(join(cwd, 'generated/pika.gen.ts'))
	})

	it('returns early when TypeScript codegen is disabled and when css output collapses to only the banner', async () => {
		const cwd = await createTempDir()
		const ctx = createCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await ctx.setup()
		vi.spyOn(ctx.engine, 'renderLayerOrderDeclaration')
			.mockReturnValue('')
		vi.spyOn(ctx.engine, 'renderPreflights')
			.mockResolvedValue('')
		vi.spyOn(ctx.engine, 'renderAtomicStyles')
			.mockResolvedValue('')

		expect(await ctx.getTsCodegenContent())
			.toBeNull()
		expect(await ctx.getCssCodegenContent())
			.toBe('/* Auto-generated by @pikacss/core */')

		await ctx.writeTsCodegenFile()
	})

	it('retries engine creation with a default plugin-only config when the initial createEngine call fails', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async (config: Record<string, unknown>) => {
				if (createEngine.mock.calls.length === 1) {
					throw new Error('boom')
				}

				return {
					config,
					use: vi.fn(async () => []),
					renderLayerOrderDeclaration: vi.fn(() => ''),
					renderPreflights: vi.fn(async () => ''),
					renderAtomicStyles: vi.fn(async () => ''),
				}
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'generated/pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect((core.createEngine as any).mock.calls)
			.toHaveLength(2)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins)
			.toHaveLength(1)
		expect((core.createEngine as any).mock.calls[1]?.[0]?.plugins?.[0]?.name)
			.toBe('@pikacss/integration:dev')
	})

	it('logs and clears setupPromise when both engine creation attempts fail', async () => {
		vi.doMock('@pikacss/core', async (importOriginal) => {
			const actual = await importOriginal<typeof import('@pikacss/core')>()
			const createEngine = vi.fn(async () => {
				throw new Error('still broken')
			})

			return {
				...actual,
				createEngine,
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const core = await import('@pikacss/core')
		const error = vi.fn()
		core.log.setErrorFn(error)
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-fallback',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'generated/pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect(error.mock.calls.some(call => call.join(' ')
			.includes('Failed to setup integration context: still broken')))
			.toBe(true)
		expect(ctx.setupPromise)
			.toBeNull()
	})

	it('returns undefined when the parser yields an unsupported function variant', async () => {
		vi.doMock('./ctx.transform-utils', async (importOriginal) => {
			const actual = await importOriginal<typeof import('./ctx.transform-utils')>()
			return {
				...actual,
				createFnUtils: () => ({
					isNormal: () => false,
					isForceString: () => false,
					isForceArray: () => false,
					isPreview: () => false,
					RE: /pika\(/g,
				}),
				findFunctionCalls: () => ([
					{
						fnName: 'pika.invalid',
						start: 14,
						end: 45,
						snippet: 'pika.invalid({ color: \'red\' })',
					},
				]),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx({
			cwd: '/tmp/pikacss-integration',
			currentPackageName: '@pikacss/core',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'generated/pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		expect(await ctx.transform('const value = pika({ color: \'red\' })', 'src/unexpected.ts'))
			.toBeUndefined()
	})

	it('swallows mkdir errors and still writes the generated file when the directory already exists', async () => {
		const cwd = await createTempDir()
		await mkdir(join(cwd, 'generated'), { recursive: true })

		vi.doMock('node:fs/promises', async (importOriginal) => {
			const actual = await importOriginal<typeof import('node:fs/promises')>()
			return {
				...actual,
				mkdir: vi.fn()
					.mockRejectedValue(new Error('EACCES: permission denied')),
			}
		})

		const { createCtx: createMockedCtx } = await import('./ctx')
		const ctx = createMockedCtx(createOptions({
			cwd,
			tsCodegen: false,
		}))

		await ctx.setup()
		await ctx.writeCssCodegenFile()

		const content = await readFile(join(cwd, 'generated/pika.gen.css'), 'utf-8')
		expect(content)
			.toContain('Auto-generated')
	})
})
