import { describe, expect, it, vi } from 'vitest'

import { generateTsCodegenContent } from './tsCodegen'

function createStubContext(options?: {
	hasVue?: boolean
	transformedFormat?: 'string' | 'array'
	renderPreview?: (atomicStyleIds: string[]) => Promise<string>
}) {
	const renderAtomicStyles = vi.fn(async (_isFormatted: boolean, input: { atomicStyleIds: string[] }) => {
		return await (options?.renderPreview?.(input.atomicStyleIds)
			?? Promise.resolve('.pk-a{color:red;}\n.pk-b{display:block;}'))
	})

	return {
		currentPackageName: '@pikacss/core',
		fnName: 'pika',
		hasVue: options?.hasVue ?? false,
		transformedFormat: options?.transformedFormat ?? 'string',
		usages: new Map([
			['src/demo.ts', [
				{
					atomicStyleIds: ['pk-a'],
					params: [{ color: 'red' }],
				},
				{
					atomicStyleIds: ['pk-b'],
					params: ['hover', { display: 'block' }],
				},
			]],
			['src/broken.ts', [
				{
					atomicStyleIds: ['broken'],
					params: [{ color: 'blue' }],
				},
			]],
			['src/non-preview.ts', [
				{
					atomicStyleIds: ['pk-d'],
					params: [{ fontSize: '16px' }],
				},
			]],
		]),
		previewUsages: new Map([
			['src/demo.ts', [
				{
					atomicStyleIds: ['pk-a'],
					params: [{ color: 'red' }],
				},
				{
					atomicStyleIds: ['pk-b'],
					params: ['hover', { display: 'block' }],
				},
			]],
			['src/broken.ts', [
				{
					atomicStyleIds: ['broken'],
					params: [{ color: 'blue' }],
				},
			]],
		]),
		engine: {
			config: {
				autocomplete: {
					selectors: new Set(['hover']),
					shortcuts: new Set(['btn']),
					extraProperties: new Set(['__important']),
					extraCssProperties: new Set(['--brand']),
					properties: new Map([
						['__important', ['boolean']],
					]),
					cssProperties: new Map([
						['color', ['red']],
					]),
					patterns: {
						selectors: new Set(['/^child-(\\d+)$/']),
						shortcuts: new Set(['/^space-(\\d+)$/']),
						properties: new Map([
							['__important', ['true | false']],
						]),
						cssProperties: new Map([
							['color', ['/^var\\(--.+\\)$/']],
						]),
					},
				},
				layers: { components: 5, utilities: 10 },
			},
			renderAtomicStyles,
		},
		log: renderAtomicStyles,
	}
}

describe('generateTsCodegenContent', () => {
	it('renders autocomplete unions, preview overloads, and Vue globals for array output mode', async () => {
		const ctx = createStubContext({
			hasVue: true,
			transformedFormat: 'array',
			renderPreview: async (atomicStyleIds) => {
				if (atomicStyleIds.includes('broken')) {
					throw new Error('boom')
				}

				return '.pk-a{color:red;}\n.pk-b{display:block;}'
			},
		})

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.toContain('// Auto-generated by @pikacss/core')
		expect(content)
			.toContain('declare module \'@pikacss/core\' {')
		expect(content)
			.toContain('Selector: "hover" | /^child-(\\d+)$/')
		expect(content)
			.toContain('Shortcut: "btn" | /^space-(\\d+)$/')
		expect(content)
			.toContain('PropertyValue: { "__important": boolean | true | false }')
		expect(content)
			.toContain('CSSPropertyValue: { "--brand": never, "color": "red" | /^var\\(--.+\\)$/ }')
		expect(content)
			.toContain('type StyleFn_Normal = StyleFn_Array')
		expect(content)
			.toContain('const pika: StyleFn')
		expect(content)
			.toContain('const pikap: StyleFnWithPreview')
		expect(content)
			.toContain('declare module \'vue\' {')
		expect(content)
			.toContain('### PikaCSS Preview')
		expect(content)
			.toMatch(/type P\d+_0 = \{"color":"red"\}/)
		expect(content)
			.toMatch(/type P\d+_0 = "hover"/)
		expect(content)
			.toMatch(/type P\d+_1 = \{"display":"block"\}/)
		expect(content)
			.not.toContain('"fontSize"')
	})

	it('falls back to never unions and omits Vue declarations when no autocomplete data exists', async () => {
		const ctx = {
			currentPackageName: '@pikacss/core',
			fnName: 'pika',
			hasVue: false,
			transformedFormat: 'string',
			usages: new Map(),
			previewUsages: new Map(),
			engine: {
				config: {
					autocomplete: {
						selectors: new Set(),
						shortcuts: new Set(),
						extraProperties: new Set(),
						extraCssProperties: new Set(),
						properties: new Map(),
						cssProperties: new Map(),
					},
					layers: {},
				},
				renderAtomicStyles: vi.fn(),
			},
		}

		const content = await generateTsCodegenContent(ctx as any)

		expect(content)
			.toContain('type StyleFn_Normal = StyleFn_String')
		expect(content)
			.toContain('Selector: never')
		expect(content)
			.toContain('Shortcut: never')
		expect(content)
			.toContain('PropertyValue: never')
		expect(content)
			.toContain('CSSPropertyValue: never')
		expect(content)
			.toContain('Layer: never')
		expect(content.includes('declare module \'vue\' {'))
			.toBe(false)
	})

	it('omits the normal style alias when transformedFormat is outside supported runtime values', async () => {
		const ctx = {
			currentPackageName: '@pikacss/core',
			fnName: 'pika',
			hasVue: false,
			transformedFormat: 'other',
			usages: new Map(),
			previewUsages: new Map(),
			engine: {
				config: {
					autocomplete: {
						selectors: new Set(),
						shortcuts: new Set(),
						extraProperties: new Set(),
						extraCssProperties: new Set(),
						properties: new Map(),
						cssProperties: new Map(),
						patterns: undefined,
					},
					layers: {},
				},
				renderAtomicStyles: vi.fn(),
			},
		}

		const content = await generateTsCodegenContent(ctx as any)

		expect(content.includes('type StyleFn_Normal = StyleFn_Array'))
			.toBe(false)
		expect(content.includes('type StyleFn_Normal = StyleFn_String'))
			.toBe(false)
	})
})
