import type { Engine, EngineConfig, Nullish } from '@pikacss/core'
import type { SourceMap } from 'magic-string'
import type { createEventHook } from './eventHook'

/**
 * Records a single `pika()` call result, pairing the resolved atomic style IDs with the original call arguments.
 *
 * @remarks
 * Each source file may produce multiple `UsageRecord` entries — one per `pika()` call site.
 * These records drive both CSS output (via `atomicStyleIds`) and IDE preview overloads (via `params`).
 */
export interface UsageRecord {
	/** The list of atomic CSS class names generated by the engine for this call. */
	atomicStyleIds: string[]
	/** The original arguments passed to `engine.use()`, preserved for TypeScript codegen overload generation. */
	params: Parameters<Engine['use']>
}

/**
 * Classifier and regex utilities for recognizing all `pika()` function call variants in source code.
 *
 * @remarks
 * The function name is configurable via `IntegrationContextOptions.fnName`, so all
 * variants (`.str`, `.arr`, preview `p` suffix, bracket notation) are derived
 * dynamically from that base name.
 */
export interface FnUtils {
	/** Returns `true` if the given function name is a normal call (output format determined by `transformedFormat`). */
	isNormal: (fnName: string) => boolean
	/** Returns `true` if the given function name forces string output (e.g., `pika.str`). */
	isForceString: (fnName: string) => boolean
	/** Returns `true` if the given function name forces array output (e.g., `pika.arr`). */
	isForceArray: (fnName: string) => boolean
	/** Returns `true` if the given function name is a preview variant (e.g., `pikap`, `pikap.str`). */
	isPreview: (fnName: string) => boolean
	/** A compiled global regex that matches all recognized function call variants, including bracket-notation accessors. */
	RE: RegExp
}

/**
 * Configuration options for creating an integration context.
 *
 * @remarks
 * These options are set by bundler plugin adapters (Vite, webpack, Nuxt) and are
 * not typically configured by end users directly.
 */
export interface IntegrationContextOptions {
	/** The working directory used to resolve relative paths for config files, codegen outputs, and source scanning. */
	cwd: string
	/** The npm package name of the integration consumer (e.g., `'@pikacss/unplugin'`), embedded in generated file headers and import paths. */
	currentPackageName: string
	/** Glob patterns controlling which source files are scanned for `pika()` calls. `include` specifies files to process; `exclude` specifies files to skip. */
	scan: {
		include: string[]
		exclude: string[]
	}
	/** The engine configuration object, a path to a config file, or `null`/`undefined` to trigger auto-discovery of `pika.config.*` files. */
	configOrPath: EngineConfig | string | Nullish
	/** The base function name to recognize in source code (e.g., `'pika'`). All variants (`.str`, `.arr`, preview) are derived from this name. */
	fnName: string
	/** Controls the default output format of normal `pika()` calls: `'string'` produces a space-joined class string, `'array'` produces a string array. */
	transformedFormat: 'string' | 'array'
	/** Path to the generated TypeScript declaration file (`pika.gen.ts`), or `false` to disable TypeScript codegen entirely. */
	tsCodegen: false | string
	/** Path to the generated CSS output file (e.g., `'pika.gen.css'`). */
	cssCodegen: string
	/** When `true`, automatically scaffolds a default `pika.config.js` file if no config file is found. */
	autoCreateConfig: boolean
}

/**
 * Discriminated union representing the outcome of loading an engine configuration file.
 *
 * @remarks
 * Three shapes are possible: an inline config (no file), a successfully loaded file-based
 * config, or a failed/missing load (all fields `null`). The `file` and `content` fields are
 * populated only when the config was loaded from disk, enabling hot-reload detection.
 */
export type LoadedConfigResult
	= | { config: EngineConfig, file: null, content: null }
		| { config: null, file: null, content: null }
		| { config: EngineConfig, file: string, content: string }

/**
 * The main build-tool integration context that bridges the PikaCSS engine with bundler plugins.
 *
 * @remarks
 * Created via `createCtx()`. The context manages the full build lifecycle: config loading,
 * engine initialization, source file transformation, usage tracking, and output file generation.
 * All transform and codegen calls automatically await `setup()` completion before proceeding.
 */
export interface IntegrationContext {
	/** The current working directory. Can be updated at runtime (e.g., when the project root changes). */
	cwd: string
	/** The npm package name of the integration consumer, used in generated file headers and module declarations. */
	currentPackageName: string
	/** The base function name recognized in source transforms (e.g., `'pika'`). */
	fnName: string
	/** The default output format for normal `pika()` calls: `'string'` or `'array'`. */
	transformedFormat: 'string' | 'array'
	/** Absolute path to the generated CSS output file, computed from `cwd` and the configured relative path. */
	cssCodegenFilepath: string
	/** Absolute path to the generated TypeScript declaration file, or `null` if TypeScript codegen is disabled. */
	tsCodegenFilepath: string | Nullish
	/** Whether the `vue` package is installed in the project, used to include Vue-specific type declarations in codegen. */
	hasVue: boolean
	/** The loaded engine configuration object, or `null` if loading failed or no config was found. */
	resolvedConfig: EngineConfig | Nullish
	/** Absolute path to the resolved config file on disk, or `null` for inline configs or when no config was loaded. */
	resolvedConfigPath: string | Nullish
	/** Raw string content of the config file, or `null` for inline configs or when no config was loaded. */
	resolvedConfigContent: string | Nullish
	/** Loads (or reloads) the engine configuration from disk or inline source, updating `resolvedConfig`, `resolvedConfigPath`, and `resolvedConfigContent`. */
	loadConfig: () => Promise<LoadedConfigResult>
	/** Map from source file ID to the list of `UsageRecord` entries extracted during transforms. Keyed by the file path relative to `cwd`. */
	usages: Map<string, UsageRecord[]>
	/** Event hooks for notifying plugins when generated outputs need refreshing. `styleUpdated` fires on CSS changes; `tsCodegenUpdated` fires on TypeScript declaration changes. */
	hooks: {
		styleUpdated: ReturnType<typeof createEventHook<void>>
		tsCodegenUpdated: ReturnType<typeof createEventHook<void>>
	}
	/** The initialized PikaCSS engine instance. Throws if accessed before `setup()` completes. */
	engine: Engine
	/** Glob patterns for the bundler's transform pipeline, derived from the scan config with codegen files excluded. */
	transformFilter: {
		include: string[]
		exclude: string[]
	}
	/** Processes a source file by extracting `pika()` calls, resolving them through the engine, and replacing them with computed output. Returns the transformed code and source map, or `null` if no calls were found. */
	transform: (code: string, id: string) => Promise<{ code: string, map: SourceMap } | Nullish>
	/** Generates the full CSS output string, including layer declarations, preflights, and all atomic styles collected from transforms. */
	getCssCodegenContent: () => Promise<string | Nullish>
	/** Generates the full TypeScript declaration content for `pika.gen.ts`, or `null` if TypeScript codegen is disabled. */
	getTsCodegenContent: () => Promise<string | Nullish>
	/** Generates and writes the CSS codegen file to disk at `cssCodegenFilepath`. */
	writeCssCodegenFile: () => Promise<void>
	/** Generates and writes the TypeScript codegen file to disk at `tsCodegenFilepath`. No-op if TypeScript codegen is disabled. */
	writeTsCodegenFile: () => Promise<void>
	/** Scans all matching source files, collects usages via transform, then writes the CSS codegen file. Used for full rebuilds. */
	fullyCssCodegen: () => Promise<void>
	/** The pending setup promise while initialization is in progress, or `null` when idle. Transform calls await this before proceeding. */
	setupPromise: Promise<void> | null
	/** Initializes (or reinitializes) the context by clearing state, loading config, creating the engine, and wiring up dev hooks. Returns a promise that resolves when setup is complete. */
	setup: () => Promise<void>
}
