import type { ProcessedCssProperty, ProcessedCssPropertyEffectMode } from './types'
import fs from 'node:fs'
import process from 'node:process'
import { fileURLToPath, pathToFileURL } from 'node:url'

import path from 'pathe'
import { loadProcessedCssData } from './index'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = path.resolve(__dirname, '..', '..', 'packages', 'core', 'src', 'generated', 'property-effects.ts')

const processedCssData = loadProcessedCssData()
const allProperties: Record<string, ProcessedCssProperty> = processedCssData.properties

type PropertyEffectMode = ProcessedCssPropertyEffectMode

function shouldIncludeProperty(property: string, shorthand: ProcessedCssProperty['shorthand']) {
	if (property === '--*')
		return false
	if (property.startsWith('--'))
		return false
	if (property.startsWith('-'))
		return false
	if (!shorthand)
		return false

	const effects = [...shorthand.longhands, ...shorthand.resetLonghands]
	if (effects.length === 0)
		return false
	return effects.every(longhand => typeof longhand === 'string' && longhand.length > 0)
}

function formatObjectRecord(record: Record<string, string[]>) {
	return Object.entries(record)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([property, longhands]) => {
			const formattedLonghands = longhands
				.map(longhand => `'${longhand}'`)
				.join(', ')
			return `\t'${property}': [${formattedLonghands}],`
		})
		.join('\n')
}

function formatStringRecord(record: Record<string, string>) {
	return Object.entries(record)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([property, value]) => `\t'${property}': '${value}',`)
		.join('\n')
}

function buildShorthandMap() {
	const shorthandMap: Record<string, string[]> = {}

	for (const [property, data] of Object.entries(allProperties)) {
		if (!shouldIncludeProperty(property, data.shorthand))
			continue

		const effects = [...data.shorthand.longhands, ...data.shorthand.resetLonghands]
		shorthandMap[property] = [...new Set(effects)].sort((left, right) => left.localeCompare(right))
	}

	return shorthandMap
}

function buildPropertyEffects(shorthandMap: Record<string, string[]>) {
	const effectCache = new Map<string, string[]>()

	function expand(property: string, stack = new Set<string>()): string[] {
		const cached = effectCache.get(property)
		if (cached != null)
			return cached

		const longhands = shorthandMap[property]
		if (longhands == null) {
			const effects = [property]
			effectCache.set(property, effects)
			return effects
		}

		if (stack.has(property))
			return longhands

		const nextStack = new Set(stack)
		nextStack.add(property)

		const effectSet = new Set<string>()
		for (const longhand of longhands) {
			for (const effect of expand(longhand, nextStack)) {
				effectSet.add(effect)
			}
		}
		const effects = [...effectSet]

		effectCache.set(property, effects)
		return effects
	}

	const effects: Record<string, string[]> = {}
	for (const property of Object.keys(allProperties)) {
		if (property === '--*' || property.startsWith('--') || property.startsWith('-'))
			continue
		effects[property] = expand(property)
	}

	return effects
}

function buildPropertyEffectModes() {
	const modes: Record<string, PropertyEffectMode> = {}
	for (const [property, data] of Object.entries(allProperties)) {
		if (property === '--*' || property.startsWith('--') || property.startsWith('-'))
			continue

		if (data.shorthand != null) {
			modes[property] = data.shorthand.mode
			continue
		}

		modes[property] = 'self'
	}

	return modes
}

export function generatePropertyEffectsOutput(): string {
	const shorthandMap = buildShorthandMap()
	const propertyEffects = buildPropertyEffects(shorthandMap)
	const propertyEffectModes = buildPropertyEffectModes()

	return [
		'// This file is auto-generated by scripts/css-data/generate-property-effects.ts.',
		'// Do not edit this file manually.',
		'',
		'export type PropertyEffectMode = \'self\' | \'shorthand\' | \'patched-shorthand\'',
		'',
		'export const PROPERTY_EFFECTS: Record<string, readonly string[]> = {',
		formatObjectRecord(propertyEffects),
		'}',
		'',
		'export const PROPERTY_EFFECT_MODES: Record<string, PropertyEffectMode> = {',
		formatStringRecord(propertyEffectModes),
		'}',
		'',
	].join('\n')
}

function main() {
	const shorthandMap = buildShorthandMap()
	const source = generatePropertyEffectsOutput()

	fs.writeFileSync(OUTPUT_PATH, source)
	console.log(`Generated ${Object.keys(shorthandMap).length} shorthand relationships at ${OUTPUT_PATH}`)
}

if (process.argv[1] != null && import.meta.url === pathToFileURL(process.argv[1]).href) {
	main()
}
