const LAYER_SELECTOR_PREFIX = '@layer '
const DEFAULT_ATOMIC_STYLE_ID_PREFIX = 'pk-'
const ATOMIC_STYLE_ID_PLACEHOLDER = '%'
const ATOMIC_STYLE_ID_PLACEHOLDER_RE_GLOBAL = /%/g

export {
	ATOMIC_STYLE_ID_PLACEHOLDER,
	ATOMIC_STYLE_ID_PLACEHOLDER_RE_GLOBAL,
	DEFAULT_ATOMIC_STYLE_ID_PREFIX,
	LAYER_SELECTOR_PREFIX,
}
